/*********************************************************************
*                                                                    *
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                                                                    *
**********************************************************************
*                                                                    *
* C-file generated by:                                               *
*                                                                    *
*        GUI_Builder for emWin version 5.32                          *
*        Compiled Oct  8 2015, 11:59:02                              *
*        (c) 2015 Segger Microcontroller GmbH & Co. KG               *
*                                                                    *
**********************************************************************
*                                                                    *
*        Internet: www.segger.com  Support: support@segger.com       *
*                                                                    *
**********************************************************************
*/

// USER START (Optionally insert additional includes)
// USER END

#include "DIALOG.h"
#include "mygui_init.h"
//#include "../usr/stay24.h"
unsigned char const zhucaidan[] = "\xe4\xb8\xbb\xe8\x8f\x9c\xe5\x8d\x95";//主菜单unsigned char const xitongshezhi[] = "1.\xe7\xb3\xbb\xe7\xbb\x9f\xe8\xae\xbe\xe7\xbd\xae";//系统设置unsigned char const xinxichaxun[] = "2.\xe4\xbf\xa1\xe6\x81\xaf\xe6\x9f\xa5\xe8\xaf\xa2";//信息查询unsigned char const pingbi[] = "3.\xe5\xb1\x8f\xe8\x94\xbd";//屏蔽unsigned char const kaifang[] = "4.\xe5\xbc\x80\xe6\x94\xbe";//开放unsigned char const zijian[] = "5.\xe8\x87\xaa\xe6\xa3\x80";//自检
/*********************************************************************
*
*       Defines
*
**********************************************************************
*/



// USER START (Optionally insert additional defines)
// USER END

/*********************************************************************
*
*       Static data
*
**********************************************************************
*/

// USER START (Optionally insert additional static data)
// USER END

/*********************************************************************
*
*       _aDialogCreate
*/
static const GUI_WIDGET_CREATE_INFO _aDialogCreate[] = {
  { WINDOW_CreateIndirect, "menu", ID_WINDOW_1, 0, 0, 480, 325, 0, 0x0, 0 },
  { TEXT_CreateIndirect, zhucaidan, ID_TEXT_0, 6, 1, 91, 26, 0, 0x0, 0 },
  { TEXT_CreateIndirect, xitongshezhi, ID_TEXT_1, 155, 46, 130, 30, 0, 0x64, 0 },
  { TEXT_CreateIndirect, xinxichaxun, ID_TEXT_2, 155, 81, 130, 30, 0, 0x64, 0 },
  { TEXT_CreateIndirect, pingbi, ID_TEXT_3, 155, 116, 130, 30, 0, 0x64, 0 },
  { TEXT_CreateIndirect, kaifang, ID_TEXT_4, 155, 151, 130, 30, 0, 0x64, 0 },
  { TEXT_CreateIndirect, zijian, ID_TEXT_5, 155, 186, 130, 30, 0, 0x64, 0 },
  { TEXT_CreateIndirect, "0", ID_TEXT_6, 277, 293, 206, 28, 0, 0x64, 0 },  { TEXT_CreateIndirect, yonghujibie, ID_TEXT_7, 6, 293, 206, 28, 0, 0x64, 0 },
  // USER START (Optionally insert additional widgets)
  // USER END
};

/*********************************************************************
*
*       Static code
*
**********************************************************************
*/

// USER START (Optionally insert additional static code)
// USER END

/*********************************************************************
*
*       _cbDialog
*/
static void _cbDialog(WM_MESSAGE * pMsg) {
  WM_HWIN hItem;
   int     NCode;
     WM_HWIN hDlg;
  // USER START (Optionally insert additional variables)
  // USER END
int keyy;
  switch (pMsg->MsgId) {  case WM_PAINT:    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_6);     _hwTime[1] = hItem;          GUI_SetColor(HFM_HEAD_BK);    GUI_FillRect(0,0,480,30);    GUI_FillRect(0,290,480,320);      	    break;
  case WM_INIT_DIALOG:
    //
    // Initialization of 'Window'
    //
    hItem = pMsg->hWin;
    WINDOW_SetBkColor(hItem, HFM_COLOR_BK);
    //
    // Initialization of 'Text'
    //    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_10);     _hwTime[1] = hItem;
    TEXT_SetFont(hItem, GUI_FONT_24_1);
    TEXT_SetTextAlign(hItem, GUI_TA_LEFT | GUI_TA_VCENTER);
    TEXT_SetText(hItem, "2018-05-08 14:53:23");
  default:



    WM_DefaultProc(pMsg);
    break;
  }
}

/*********************************************************************
*
*       Public code
*
**********************************************************************
*/
/*********************************************************************
*
*       CreateWindow
*/
WM_HWIN Create_menu_Window(void);
WM_HWIN Create_menu_Window(void) {
  WM_HWIN hWin;
  //WM_SetCallback(WM_HBKWIN, _cbEditAddKey);
  hWin = GUI_CreateDialogBox(_aDialogCreate, GUI_COUNTOF(_aDialogCreate), _cbDialog, WM_HBKWIN, 0, 0);
  return hWin;
}

// USER START (Optionally insert additional public code)
// USER END

/*************************** End of file ****************************/
