/*********************************************************************
*                                                                    *
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                                                                    *
**********************************************************************
*                                                                    *
* C-file generated by:                                               *
*                                                                    *
*        GUI_Builder for emWin version 5.32                          *
*        Compiled Oct  8 2015, 11:59:02                              *
*        (c) 2015 Segger Microcontroller GmbH & Co. KG               *
*                                                                    *
**********************************************************************
*                                                                    *
*        Internet: www.segger.com  Support: support@segger.com       *
*                                                                    *
**********************************************************************
*/

// USER START (Optionally insert additional includes)
// USER END

#include "DIALOG.h"#include "mygui_init.h"

/*********************************************************************
*
*       Defines
*
**********************************************************************
*/
#define ID_WINDOW_0 (GUI_ID_USER + 0x00)
#define ID_TEXT_0 (GUI_ID_USER + 0x01)
#define ID_TEXT_1 (GUI_ID_USER + 0x02)
#define ID_TEXT_2 (GUI_ID_USER + 0x03)
#define ID_TEXT_3 (GUI_ID_USER + 0x04)
#define ID_TEXT_4 (GUI_ID_USER + 0x05)
#define ID_TEXT_5 (GUI_ID_USER + 0x06)
#define ID_TEXT_6 (GUI_ID_USER + 0x07)#define ID_TEXT_7 (GUI_ID_USER + 0x08)#define ID_EDIT_0 (GUI_ID_USER + 0x09)#define ID_EDIT_1 (GUI_ID_USER + 0x0A)#define ID_EDIT_2 (GUI_ID_USER + 0x0B)#define ID_EDIT_3 (GUI_ID_USER + 0x0C)
// USER START (Optionally insert additional defines)
// USER END

/*********************************************************************
*
*       Static data
*
**********************************************************************
*/
unsigned char crttongxinshezhi[] = "CRT\xe9\x80\x9a\xe8\xae\xaf\xe8\xae\xbe\xe7\xbd\xae";unsigned char xunyu[] = "\xe5\x85\x81\xe8\xae\xb8:";unsigned char leixx[] = "\xe7\xb1\xbb\xe5\x9e\x8b\xef\xbc\x9a";unsigned char baojingfasong[] ="\xe6\x8a\xa5\xe8\xad\xa6\xe5\x8f\x91\xe9\x80\x81\xef\xbc\x9a:";unsigned char guzhangfasong[] = "\xe6\x95\x85\xe9\x9a\x9c\xe5\x8f\x91\xe9\x80\x81\xef\xbc\x9a:";unsigned char qitafasong[] = "\xe5\x85\xb6\xe4\xbb\x96\xe5\x8f\x91\xe9\x80\x81\xef\xbc\x9a:";unsigned char infoo1[] = "\xe6\x8c\x89<F1>\xe9\x94\xae\xe9\x80\x89\xe6\x8b\xa9\xe7\xb1\xbb\xe5\x9e\x8b:";unsigned char inff002[] = "CRT/\xe4\xbc\xa0\xe8\xbe\x93\xe8\xae\xbe\xe5\xa4\x87/BA\xe6\xa8\xa1\xe5\xbc\x8f";
// USER START (Optionally insert additional static data)
// USER END

/*********************************************************************
*
*       _aDialogCreate
*/
static const GUI_WIDGET_CREATE_INFO _aDialogCreate[] = {
  { WINDOW_CreateIndirect, "Window", ID_WINDOW_0, 0, 0, 480, 320, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "0", ID_TEXT_0, 277, 293, 206, 28, 0, 0x0, 0 },
  { TEXT_CreateIndirect, yonghujibie, ID_TEXT_1, 6, 293, 130, 30, 0, 0x0, 0 },
  { TEXT_CreateIndirect, crttongxinshezhi, ID_TEXT_2, 6, 1, 130, 30, 0, 0x0, 0 },  { TEXT_CreateIndirect, xunyu, ID_TEXT_3, 112, 46, 80, 30, 0, 0x0, 0 },  { TEXT_CreateIndirect, leixx, ID_TEXT_4, 112, 94, 80, 30, 0, 0x0, 0 },  { TEXT_CreateIndirect, baojingfasong, ID_TEXT_5, 62, 142, 110, 30, 0, 0x0, 0 },  { TEXT_CreateIndirect, guzhangfasong, ID_TEXT_6, 62, 190, 110, 30, 0, 0x0, 0 },  { TEXT_CreateIndirect, qitafasong, ID_TEXT_7, 62, 238, 110, 30, 0, 0x0, 0 },  { EDIT_CreateIndirect, "Edit", ID_EDIT_0, 172, 46, 39, 24, 0, 0x1, 0 },  { EDIT_CreateIndirect, "Edit", ID_EDIT_1, 172, 142, 39, 24, 0, 0x1, 0 },  { EDIT_CreateIndirect, "Edit", ID_EDIT_2, 172, 190, 39, 24, 0, 0x1, 0 },  { EDIT_CreateIndirect, "Edit", ID_EDIT_3, 172, 238, 39, 24, 0, 0x1, 0 },
  // USER START (Optionally insert additional widgets)
  // USER END
};

/*********************************************************************
*
*       Static code
*
**********************************************************************
*/

// USER START (Optionally insert additional static code)
// USER END

/*********************************************************************
*
*       _cbDialog
*/
static void _cbDialog(WM_MESSAGE * pMsg) {
  WM_HWIN hItem;  unsigned char userstring[30];
  // USER START (Optionally insert additional variables)
  // USER END

  switch (pMsg->MsgId) {  case WM_PAINT :    if(WM_Paint_Flag == 1)    {        WM_Paint_Flag = 0;       GUI_SetColor(HFM_HEAD_BK);       GUI_FillRect(0,0,480,30);       GUI_FillRect(0,290,480,320);       GUI_SetBkColor(HFM_COLOR_BK);       GUI_SetColor(HFM_COLOR_BY);       GUI_SetFont(&GUI_Fontstay24);       GUI_DispStringAt(infoo1,240,142);       GUI_DispStringAt(inff002,240,182);          //显示密码级别       hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_1);       sprintf(userstring,"\xe7\x94\xa8\xe6\x88\xb7\xe7\xba\xa7\xe5\x88\xab:%d",userlevel);
       TEXT_SetText(hItem, userstring);//    }    break;
  case WM_INIT_DIALOG:
    //
    // Initialization of 'Window'
    //
        hItem = pMsg->hWin;
        WINDOW_SetBkColor(hItem, HFM_COLOR_BK);
    // USER START (Optionally insert additional code for further widget initialization)        hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_0);        _hwTime[12] = hItem;
       TEXT_SetFont(hItem, GUI_FONT_24_1);
       TEXT_SetTextAlign(hItem, GUI_TA_LEFT | GUI_TA_VCENTER);
       TEXT_SetText(hItem, timee);       hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_0);       EDIT_EnableBlink(hItem, 300, 1);       EDIT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);       EDIT_SetFont(hItem, GUI_FONT_20_ASCII);     //  EDIT_EnableBlink(hItem, 300, 1);    //    // Initialization of 'Edit'    //      hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_1);      EDIT_EnableBlink(hItem, 300, 1);      EDIT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);      EDIT_SetFont(hItem, GUI_FONT_20_ASCII);    //    // Initialization of 'Edit'    //      hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_2);      EDIT_EnableBlink(hItem, 300, 1);      EDIT_SetFont(hItem, GUI_FONT_20_1);      EDIT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);    //    // Initialization of 'Edit'    //     hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_3);     EDIT_EnableBlink(hItem, 300, 1);     EDIT_SetFont(hItem, GUI_FONT_20_1);     EDIT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
    // USER START (Optionally insert additional code for further widget initialization)
    // USER END
    break;
  // USER START (Optionally insert additional message handling)
  // USER END
  default:
    WM_DefaultProc(pMsg);
    break;
  }
}

/*********************************************************************
*
*       Public code
*
**********************************************************************
*/void W13_CrtSetWindowDisplay(void)
{

}
void W13_CrtSetWindowProcess(void)
{
     switch(WinKeyValue)
     {
     case GUI_KEY_ENTER://ok键

          break;
     case GUI_KEY_HOME://菜单按钮
          break;
     case GUI_KEY_LEFT://左键
          break;
	 case GUI_KEY_UP://下键
          break;
	 case GUI_KEY_DOWN://下键
          break;
	 case GUI_KEY_ESCAPE://取消键
            break;
	case GUI_USR_KEY_ALARM://火警界面键
        break;
	case GUI_USR_KEY_FAULT://故障界面键
        break;
	case GUI_USR_KEY_SHEILD://屏蔽界面键
	    break;
	case GUI_USR_KEY_OUT://输出界面键
		break;
	case GUI_USR_KEY_SLIENCE://消音键
		break;
	case GUI_USR_KEY_RESET://复位键
		break;
	case GUI_KEY_F1://F1功能键
		break;
	case GUI_KEY_F2://F2功能键
		break;
	case '0':
		break;
	case '1':
	case '2':
	case '3':
	case '4':
    case '5':
	case '6':
	case '7':
	case '8':
	case '9':
		break;
	default :
			break;
     }
}
/*********************************************************************
*
*       CreateWindow
*/

WM_HWIN Create_W13_CRTSET_Window(void) {
  WM_HWIN hWin;

  hWin = GUI_CreateDialogBox(_aDialogCreate, GUI_COUNTOF(_aDialogCreate), _cbDialog, WM_HBKWIN, 0, 0);
  return hWin;
}

// USER START (Optionally insert additional public code)
// USER END

/*************************** End of file ****************************/
