/*********************************************************************
*                                                                    *
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                                                                    *
**********************************************************************
*                                                                    *
* C-file generated by:                                               *
*                                                                    *
*        GUI_Builder for emWin version 5.32                          *
*        Compiled Oct  8 2015, 11:59:02                              *
*        (c) 2015 Segger Microcontroller GmbH & Co. KG               *
*                                                                    *
**********************************************************************
*                                                                    *
*        Internet: www.segger.com  Support: support@segger.com       *
*                                                                    *
**********************************************************************
*/

// USER START (Optionally insert additional includes)
// USER END

#include "DIALOG.h"#include "mygui_init.h"
/*********************************************************************
*
*       Defines
*
**********************************************************************
*/

unsigned char xinxchaxun[]   = "\xe4\xbf\xa1\xe6\x81\xaf\xe6\x9f\xa5\xe8\xaf\xa2";unsigned char baojingxinxi[] ="1.\xe6\x8a\xa5\xe8\xad\xa6\xe4\xbf\xa1\xe6\x81\xaf";unsigned char shijianxinxi[] ="2.\xe4\xba\x8b\xe4\xbb\xb6\xe4\xbf\xa1\xe6\x81\xaf";unsigned char pingbixinxi[]  = "3.\xe5\xb1\x8f\xe8\x94\xbd\xe4\xbf\xa1\xe6\x81\xaf";unsigned char shuchuxinxi[]  = "4.\xe8\xbe\x93\xe5\x87\xba\xe4\xbf\xa1\xe6\x81\xaf";unsigned char xitongxinxi[]  = "5.\xe7\xb3\xbb\xe7\xbb\x9f\xe4\xbf\xa1\xe6\x81\xaf";

// USER START (Optionally insert additional defines)
// USER END

/*********************************************************************
*
*       Static data
*
**********************************************************************
*/

// USER START (Optionally insert additional static data)
// USER END

/*********************************************************************
*
*       _aDialogCreate
*/
static const GUI_WIDGET_CREATE_INFO _aDialogCreate[] = {
  { FRAMEWIN_CreateIndirect, "Framewin", ID_FRAMEWIN_3, -4, -4, 490, 340, 0, 0x0, 0 },
  { TEXT_CreateIndirect, xinxchaxun, ID_TEXT_20, 6, 4, 130, 30, 0, 0x0, 0 },
  { TEXT_CreateIndirect, baojingxinxi, ID_TEXT_21, 155, 46, 130, 30, 0, 0x0, 0 },
  { TEXT_CreateIndirect, shijianxinxi, ID_TEXT_22, 155, 81, 130, 30, 0, 0x0, 0 },
  { TEXT_CreateIndirect, pingbixinxi, ID_TEXT_23, 155, 116, 130, 30, 0, 0x0, 0 },
  { TEXT_CreateIndirect, shuchuxinxi, ID_TEXT_24, 155, 151, 130, 30, 0, 0x0, 0 },
  { TEXT_CreateIndirect, xitongxinxi, ID_TEXT_25, 155, 186, 130, 30, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "Text", ID_TEXT_26, 277, 293, 206, 28, 0, 0x0, 0 },
  // USER START (Optionally insert additional widgets)
  // USER END
};

/*********************************************************************
*
*       Static code
*
**********************************************************************
*/

// USER START (Optionally insert additional static code)
// USER END

/*********************************************************************
*
*       _cbDialog
*/
static void _cbDialog(WM_MESSAGE * pMsg) {
  WM_HWIN hItem;
  // USER START (Optionally insert additional variables)
  // USER END

  switch (pMsg->MsgId) {
  case WM_INIT_DIALOG:
    //
    // Initialization of 'Framewin'
    //    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_26);    _hwTime[3] = hItem;        TEXT_SetFont(hItem, GUI_FONT_24_1);
    TEXT_SetTextAlign(hItem, GUI_TA_LEFT | GUI_TA_VCENTER);
    hItem = pMsg->hWin;
    FRAMEWIN_SetTextColor(hItem, GUI_MAKE_COLOR(0x00808040));
    FRAMEWIN_SetTitleVis(hItem, 0);
    // USER START (Optionally insert additional code for further widget initialization)
    // USER END
    break;
  // USER START (Optionally insert additional message handling)
  // USER END
  default:
    WM_DefaultProc(pMsg);
    break;
  }
}

/*********************************************************************
*
*       Public code
*
**********************************************************************
*/
/*********************************************************************
*
*       CreateFramewin
*/

WM_HWIN Create_W3_EventQuery_Framewin(void) {
  WM_HWIN hWin;

  hWin = GUI_CreateDialogBox(_aDialogCreate, GUI_COUNTOF(_aDialogCreate), _cbDialog, WM_HBKWIN, 0, 0);
  return hWin;
}

// USER START (Optionally insert additional public code)
// USER END

/*************************** End of file ****************************/
