/*********************************************************************
*                                                                    *
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                                                                    *
**********************************************************************
*                                                                    *
* C-file generated by:                                               *
*                                                                    *
*        GUI_Builder for emWin version 5.32                          *
*        Compiled Oct  8 2015, 11:59:02                              *
*        (c) 2015 Segger Microcontroller GmbH & Co. KG               *
*                                                                    *
**********************************************************************
*                                                                    *
*        Internet: www.segger.com  Support: support@segger.com       *
*                                                                    *
**********************************************************************
*/

// USER START (Optionally insert additional includes)
// USER END

#include "DIALOG.h"#include "mygui_init.h"


unsigned char const xitongshezhi_[] = "\xe7\xb3\xbb\xe7\xbb\x9f\xe8\xae\xbe\xe7\xbd\xae";//系统设置
unsigned char const shijianshezhi[] = "1.\xe6\x97\xb6\xe9\x97\xb4\xe8\xae\xbe\xe7\xbd\xae";//时间设置unsigned char const dayinshezhi[] = "2.\xe6\x89\x93\xe5\x8d\xb0\xe8\xae\xbe\xe7\xbd\xae";//打印设置unsigned char const mimashezhi[] = "3.\xe5\xaf\x86\xe7\xa0\x81\xe8\xae\xbe\xe7\xbd\xae";//密码设置unsigned char const canshushezhi[] = "4.\xe5\x8f\x82\xe6\x95\xb0\xe8\xae\xbe\xe7\xbd\xae";//参数设置unsigned char const tongxunshezhi[] = "5.\xe9\x80\x9a\xe8\xae\xaf\xe8\xae\xbe\xe7\xbd\xae";//通讯设置unsigned char const xitongchushihua[] = "6.\xe7\xb3\xbb\xe7\xbb\x9f\xe5\x88\x9d\xe5\xa7\x8b\xe5\x8c\x96";//系统初始化unsigned char const xitongshengji[] = "7.\xe7\xb3\xbb\xe7\xbb\x9f\xe5\x8d\x87\xe7\xba\xa7";//系统升级

// USER START (Optionally insert additional defines)
// USER END
#define ID_WINDOW_0 (GUI_ID_USER + 0x00)
#define ID_TEXT_0 (GUI_ID_USER + 0x01)
#define ID_TEXT_1 (GUI_ID_USER + 0x02)
#define ID_TEXT_2 (GUI_ID_USER + 0x03)
#define ID_TEXT_3 (GUI_ID_USER + 0x04)
#define ID_TEXT_4 (GUI_ID_USER + 0x05)
#define ID_TEXT_5 (GUI_ID_USER + 0x06)
#define ID_TEXT_6 (GUI_ID_USER + 0x07)#define ID_TEXT_7 (GUI_ID_USER + 0x08)#define ID_TEXT_8 (GUI_ID_USER + 0x09)#define ID_TEXT_9 (GUI_ID_USER + 0x0A)
/*********************************************************************
*
*       Static data
*
**********************************************************************
*/

// USER START (Optionally insert additional static data)
// USER END

/*********************************************************************
*
*       _aDialogCreate
*/
static const GUI_WIDGET_CREATE_INFO _aDialogCreate[] = {
  { WINDOW_CreateIndirect, "SystemSet", ID_WINDOW_0, 0, 0, 480, 325, 0, 0x0, 0 },
  { TEXT_CreateIndirect, xitongshezhi_, ID_TEXT_0, 6, 1, 130, 30, 0, 0x0, 0 },
  { TEXT_CreateIndirect, shijianshezhi, ID_TEXT_1, 155, 46, 130, 30, 0, 0x0, 0 },
  { TEXT_CreateIndirect, dayinshezhi, ID_TEXT_2, 155, 81, 130, 30, 0, 0x0, 0 },
  { TEXT_CreateIndirect, mimashezhi, ID_TEXT_3, 155, 116, 130, 30, 0, 0x0, 0 },
  { TEXT_CreateIndirect, canshushezhi, ID_TEXT_4, 155, 151, 130, 30, 0, 0x0, 0 },
  { TEXT_CreateIndirect, tongxunshezhi, ID_TEXT_5, 155, 186, 130, 30, 0, 0x0, 0 },
  { TEXT_CreateIndirect, xitongchushihua, ID_TEXT_6, 155, 221, 145, 30, 0, 0x0, 0 },
  { TEXT_CreateIndirect, xitongshengji, ID_TEXT_7, 155, 256, 130, 30, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "0", ID_TEXT_8, 277, 293, 206, 28, 0, 0x0, 0 },
  { TEXT_CreateIndirect, yonghujibie, ID_TEXT_9, 6, 293, 206, 28, 0, 0x0, 0 },
  // USER START (Optionally insert additional widgets)
  // USER END
};

/*********************************************************************
*
*       Static code
*
**********************************************************************
*/

// USER START (Optionally insert additional static code)
// USER END

/*********************************************************************
*
*       _cbDialog
*/
static void _cbDialog(WM_MESSAGE * pMsg) {
  WM_HWIN hItem;  unsigned char userstring[30];
  // USER START (Optionally insert additional variables)
  // USER END

  switch (pMsg->MsgId) {
  	case WM_PAINT :      if(WM_Paint_Flag == 1)      {          WM_Paint_Flag = 0;
		GUI_SetColor(HFM_HEAD_BK);
		GUI_FillRect(0,0,480,30);
		GUI_FillRect(0,290,480,320);           //显示用户级别       hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_9);       sprintf(userstring,"\xe7\x94\xa8\xe6\x88\xb7\xe7\xba\xa7\xe5\x88\xab:%d",userlevel);
       TEXT_SetText(hItem, userstring);//     }
		break;
  case WM_INIT_DIALOG:
    //
    // Initialization of 'Window'
    //
    hItem = pMsg->hWin;
    WINDOW_SetBkColor(hItem, HFM_COLOR_BK);
    // USER START (Optionally insert additional code for further widget initialization)
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_8);
    _hwTime[2] = hItem;
    TEXT_SetFont(hItem, GUI_FONT_24_1);
    TEXT_SetTextAlign(hItem, GUI_TA_LEFT | GUI_TA_VCENTER);
    TEXT_SetText(hItem, timee);
    // USER END
    break;
  // USER START (Optionally insert additional message handling)
  // USER END
  default:
    WM_DefaultProc(pMsg);
    break;
  }
}

/*********************************************************************
*
*       Public code
*
**********************************************************************
*/void W3_SystemWindowDisplay(void)
{

}
void W3_SystemWindowProcess(void)
{
     switch(WinKeyValue)
     {
     case GUI_KEY_ENTER://ok键

          break;
     case GUI_KEY_HOME://菜单按钮
          break;
     case GUI_KEY_LEFT://左键
          break;
	 case GUI_KEY_UP://下键
          break;
	 case GUI_KEY_DOWN://下键
          break;
	 case GUI_KEY_ESCAPE://取消键
            break;
	case GUI_USR_KEY_ALARM://火警界面键
        break;
	case GUI_USR_KEY_FAULT://故障界面键
        break;
	case GUI_USR_KEY_SHEILD://屏蔽界面键
	    break;
	case GUI_USR_KEY_OUT://输出界面键
		break;
	case GUI_USR_KEY_SLIENCE://消音键
		break;
	case GUI_USR_KEY_RESET://复位键
		break;
	case GUI_KEY_F1://F1功能键
		break;
	case GUI_KEY_F2://F2功能键
		break;
	case '0':
		break;
	case '1':
	case '2':
	case '3':
	case '4':
    case '5':
	case '6':
	case '7':
	case '8':
	case '9':
		break;
	default :
			break;
     }
}
/*********************************************************************
*
*       CreateWindow
*/
WM_HWIN Create_SysSet_Window(void);
WM_HWIN Create_SysSet_Window(void) {
  WM_HWIN hWin;

  hWin = GUI_CreateDialogBox(_aDialogCreate, GUI_COUNTOF(_aDialogCreate), _cbDialog, WM_HBKWIN, 0, 0);
  return hWin;
}

// USER START (Optionally insert additional public code)
// USER END

/*************************** End of file ****************************/
