/*********************************************************************
*                                                                    *
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                                                                    *
**********************************************************************
*                                                                    *
* C-file generated by:                                               *
*                                                                    *
*        GUI_Builder for emWin version 5.32                          *
*        Compiled Oct  8 2015, 11:59:02                              *
*        (c) 2015 Segger Microcontroller GmbH & Co. KG               *
*                                                                    *
**********************************************************************
*                                                                    *
*        Internet: www.segger.com  Support: support@segger.com       *
*                                                                    *
**********************************************************************
*/

// USER START (Optionally insert additional includes)
// USER END

#include "DIALOG.h"
#include "mygui_init.h"#include <time.h>#include <stdio.h>#include <stdlib.h>
/*********************************************************************
*
*       Defines
*
**********************************************************************
*/
#define ID_WINDOW_0 (GUI_ID_USER + 0x06)
#define ID_TEXT_0 (GUI_ID_USER + 0x07)
#define ID_EDIT_0 (GUI_ID_USER + 0x08)
#define ID_TEXT_1 (GUI_ID_USER + 0x09)
#define ID_TEXT_2 (GUI_ID_USER + 0x0A)
#define ID_EDIT_1 (GUI_ID_USER + 0x0B)
#define ID_TEXT_3 (GUI_ID_USER + 0x0C)
#define ID_TEXT_4 (GUI_ID_USER + 0x0D)
unsigned char riqi[] = "\xe6\x97\xa5\xe6\x9c\x9f\xef\xbc\x9a";unsigned char shijian[] = "\xe6\x97\xb6\xe9\x97\xb4\xef\xbc\x9a";

// USER START (Optionally insert additional defines)
// USER END
unsigned char const shijiansezhi[] = "\xe6\x97\xb6\xe9\x97\xb4\xe8\xae\xbe\xe7\xbd\xae";
/*********************************************************************
*
*       Static data
*
**********************************************************************
*/

// USER START (Optionally insert additional static data)
// USER END

/*********************************************************************
*
*       _aDialogCreate
*/
static const GUI_WIDGET_CREATE_INFO _aDialogCreate[] = {
  { WINDOW_CreateIndirect, "Window", ID_WINDOW_0, 0, 0, 480, 320, 0, 0x0, 0 },
  { TEXT_CreateIndirect, shijiansezhi, ID_TEXT_0, 6, 1, 130, 30, 0, 0x0, 0 },
  { EDIT_CreateIndirect, "Edit", ID_EDIT_0, 169, 83, 97, 24, 0, 10, 0 },
  { TEXT_CreateIndirect, riqi, ID_TEXT_1, 97, 83, 61, 30, 0, 0x0, 0 },
  { TEXT_CreateIndirect, shijian, ID_TEXT_2, 97, 123, 65, 30, 0, 0x0, 0 },
  { EDIT_CreateIndirect, "Edit", ID_EDIT_1, 169, 123, 97, 24, 0, 8, 0 },
  { TEXT_CreateIndirect, yonghujibie, ID_TEXT_3, 6, 293, 206, 28, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "Text", ID_TEXT_4, 277, 293, 206, 28, 0, 0x0, 0 },
  // USER START (Optionally insert additional widgets)
  // USER END
};

/*********************************************************************
*
*       Static code
*
**********************************************************************
*/

// USER START (Optionally insert additional static code)
// USER END

/*********************************************************************
*
*       _cbDialog
*/
static void _cbDialog(WM_MESSAGE * pMsg) {
  WM_HWIN hItem;
  int     NCode;
  int     Id;  unsigned char userstring[30];
  // USER START (Optionally insert additional variables)
  // USER END

  switch (pMsg->MsgId) {    case WM_PAINT :         if(WM_Paint_Flag == 1)         {             WM_Paint_Flag = 0;            GUI_SetColor(HFM_HEAD_BK);            GUI_FillRect(0,0,480,30);            GUI_FillRect(0,290,480,320);            hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_0);            EDIT_EnableBlink(hItem, 300, 1);            EDIT_SetFont(hItem, GUI_FONT_20_1);            EDIT_SetText(hItem,"");            hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_1);            EDIT_SetFont(hItem, GUI_FONT_20_1);            EDIT_EnableBlink(hItem, 300, 1);            EDIT_SetText(hItem,"");               //显示用户级别            hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_3);            sprintf(userstring,"\xe7\x94\xa8\xe6\x88\xb7\xe7\xba\xa7\xe5\x88\xab:%d",userlevel);
            TEXT_SetText(hItem, userstring);//         }      //hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_0);    // WM_SetFocus(hItem);    break;
  case WM_INIT_DIALOG:
    //
    // Initialization of 'Window'
    //

    //
    // Initialization of 'Edit'
    //
    hItem = pMsg->hWin;
    WINDOW_SetBkColor(hItem, HFM_COLOR_BK);
    // USER START (Optionally insert additional code for further widget initialization)        hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_4);        _hwTime[4] = hItem;
    TEXT_SetFont(hItem, GUI_FONT_24_1);
    TEXT_SetTextAlign(hItem, GUI_TA_LEFT | GUI_TA_VCENTER);
    TEXT_SetText(hItem, timee);     //WM_SetFocus(hItem);
    // USER START (Optionally insert additional code for further widget initialization)
    // USER END
    break;
  case WM_NOTIFY_PARENT:
    Id    = WM_GetId(pMsg->hWinSrc);
    NCode = pMsg->Data.v;
    switch(Id) {
    case ID_EDIT_0: // Notifications sent by 'Edit'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_VALUE_CHANGED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_EDIT_1: // Notifications sent by 'Edit'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_VALUE_CHANGED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    // USER START (Optionally insert additional code for further Ids)
    // USER END
    }
    break;    case WM_KEY:
  // USER START (Optionally insert additional message handling)
  // USER END
  default:
    WM_DefaultProc(pMsg);
    break;
  }
}

/*********************************************************************
*
*       Public code
*
**********************************************************************
*/void W5_TimeSetWindowDisplay(void)
{   // WM_HWIN active_Win;
   // active_Win =  WM_GetActiveWindow(); //  WM_SetFocus(W5_TimeSet_window);
}
void W5_TimeSetWindowProcess(void)
{    static unsigned char flag = 0;    unsigned char errflag = 0;    EDIT_Handle timeset;    unsigned char tempstr_year[5] = {0,},tempstr_month[3] = {0,},tempstr_day[3] = {0,},tempstr_hour[3] = {0,},tempstr_min[3] = {0,},tempstr_sec[3] = {0,};    struct tm timedata;    static unsigned char bufftemp[11];    static unsigned char editflag = 0;    WM_SetFocus(W5_TimeSet_window);
     switch(WinKeyValue)
     {
     case GUI_KEY_ENTER://ok键
         timeset = WM_GetDialogItem(W5_TimeSet_window, ID_EDIT_0);         EDIT_GetText(timeset,bufftemp,11);//获取日期         strncpy(tempstr_year,bufftemp,4);//得到年         timedata.tm_year   =atoi(tempstr_year);         strncpy(tempstr_month,bufftemp+5,2);//得到月         timedata.tm_mon = atoi(tempstr_month);         if((timedata.tm_mon == 0)||(timedata.tm_mon > 12))         {             errflag = 1;         }         strncpy(tempstr_day,bufftemp+8,2);//得到日         timedata.tm_mday = atoi(tempstr_day);         if((timedata.tm_mday == 0)||(timedata.tm_mday > 31))         {             errflag = 1;         }         timeset = WM_GetDialogItem(W5_TimeSet_window, ID_EDIT_1);         EDIT_GetText(timeset,bufftemp,9);         strncpy(tempstr_hour,bufftemp,2);         timedata.tm_hour   =atoi(tempstr_hour);         if(timedata.tm_hour > 23)         {             errflag = 1;         }         strncpy(tempstr_min,bufftemp+3,2);         timedata.tm_min = atoi(tempstr_min);         if((timedata.tm_min > 60))         {             errflag = 1;         }         strncpy(tempstr_sec,bufftemp+6,2);         timedata.tm_sec = atoi(tempstr_sec);         if((timedata.tm_sec > 60))         {             errflag = 1;         }         if(flag == 0 )         {             flag = 1;             if(errflag == 0)             {                Show_Message(WIN_SUCESS_WRITE);                //添加保存时间函数             }             else             {                 Show_Message(WIN_ERR_DATA);             }         }         else         {             flag = 0;             WM_HideWin(W_MessageBox);         }
          break;
     case GUI_KEY_HOME://菜单按钮
          break;
     case GUI_KEY_LEFT://左键
          break;
	 case GUI_KEY_UP://下键
	 case GUI_KEY_DOWN://下键          GUI_SendKeyMsg(GUI_KEY_TAB, 1);
          break;
	 case GUI_KEY_ESCAPE://取消键           flag == 0;
            break;
	case GUI_USR_KEY_ALARM://火警界面键
        break;
	case GUI_USR_KEY_FAULT://故障界面键
        break;
	case GUI_USR_KEY_SHEILD://屏蔽界面键
	    break;
	case GUI_USR_KEY_OUT://输出界面键
		break;
	case GUI_USR_KEY_SLIENCE://消音键
		break;
	case GUI_USR_KEY_RESET://复位键
		break;
	case GUI_KEY_F1://F1功能键/破折号         GUI_SendKeyMsg(GUI_USR_KEY_DASH, 1);
		break;
	case GUI_KEY_F2://F2功能键/删除         GUI_SendKeyMsg(GUI_KEY_BACKSPACE, 1);
		break;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
    case '5':
	case '6':
	case '7':
	case '8':
	case '9':   //     GUI_SendKeyMsg(WinKeyValue, 1);
		break;
	default :
			break;
     }
}
/*********************************************************************
*
*       CreateWindow
*/

WM_HWIN Create_W5_TimeSet_Window(void) {
  WM_HWIN hWin;

  hWin = GUI_CreateDialogBox(_aDialogCreate, GUI_COUNTOF(_aDialogCreate), _cbDialog, WM_HBKWIN, 0, 0);
  return hWin;
}

// USER START (Optionally insert additional public code)
// USER END

/*************************** End of file ****************************/
