/*********************************************************************
*                                                                    *
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                                                                    *
**********************************************************************
*                                                                    *
* C-file generated by:                                               *
*                                                                    *
*        GUI_Builder for emWin version 5.32                          *
*        Compiled Oct  8 2015, 11:59:02                              *
*        (c) 2015 Segger Microcontroller GmbH & Co. KG               *
*                                                                    *
**********************************************************************
*                                                                    *
*        Internet: www.segger.com  Support: support@segger.com       *
*                                                                    *
**********************************************************************
*/

// USER START (Optionally insert additional includes)
// USER END

#include "DIALOG.h"#include "mygui_init.h"

/*********************************************************************
*
*       Defines
*
**********************************************************************
*/
#define ID_WINDOW_0 (GUI_ID_USER + 0x00)
#define ID_TEXT_0 (GUI_ID_USER + 0x01)
#define ID_TEXT_1 (GUI_ID_USER + 0x02)
#define ID_TEXT_2 (GUI_ID_USER + 0x03)
#define ID_TEXT_3 (GUI_ID_USER + 0x04)
#define ID_TEXT_4 (GUI_ID_USER + 0x05)
#define ID_TEXT_5 (GUI_ID_USER + 0x06)
#define ID_TEXT_6 (GUI_ID_USER + 0x07)#define ID_TEXT_7 (GUI_ID_USER + 0x0C)#define ID_EDIT_0 (GUI_ID_USER + 0x08)#define ID_EDIT_1 (GUI_ID_USER + 0x09)#define ID_EDIT_2 (GUI_ID_USER + 0x0A)#define ID_EDIT_3 (GUI_ID_USER + 0x0B)


// USER START (Optionally insert additional defines)
// USER END
unsigned char dayinsezhi[] = "\xe6\x89\x93\xe5\x8d\xb0\xe8\xae\xbe\xe7\xbd\xae";unsigned char quanbudayin[] ="1.\xe5\x85\xa8\xe9\x83\xa8\xe6\x89\x93\xe5\x8d\xb0\xef\xbc\x9a";unsigned char baojingdayin[] = "2.\xe6\x8a\xa5\xe8\xad\xa6\xe6\x89\x93\xe5\x8d\xb0\xef\xbc\x9a";unsigned char guzhangdayin[] = "3.\xe6\x95\x85\xe9\x9a\x9c\xe6\x89\x93\xe5\x8d\xb0\xef\xbc\x9a";unsigned char qitadayin[] = "4.\xe5\x85\xb6\xe4\xbb\x96\xe6\x89\x93\xe5\x8d\xb0\xef\xbc\x9a";unsigned char w6_info[] = "\xe6\x8c\x89<F1>\xe9\x94\xae\xe9\x80\x89\xe6\x8b\xa9Y/N,<\xe4\xb8\x8a\xe4\xb8\x8b>\xe9\x94\xae\xe7\xa7\xbb\xe5\x8a\xa8\xe5\x85\x89\xe6\xa0\x87\xe3\x80\x82";
/*********************************************************************
*
*       Static data
*
**********************************************************************
*/
static unsigned char cursor = 0;
// USER START (Optionally insert additional static data)
// USER END

/*********************************************************************
*
*       _aDialogCreate
*/
static const GUI_WIDGET_CREATE_INFO _aDialogCreate[] = {
  { WINDOW_CreateIndirect, "Window", ID_WINDOW_0, 0, 0, 480, 320, 0, 0x0, 0 },
  { TEXT_CreateIndirect, dayinsezhi, ID_TEXT_0, 6, 1, 130, 30, 0, 0x0, 0 },
  { TEXT_CreateIndirect, quanbudayin, ID_TEXT_1, 155, 46, 130, 30, 0, 0x0, 0 },
  { TEXT_CreateIndirect, baojingdayin, ID_TEXT_2, 155, 81, 130, 30, 0, 0x0, 0 },
  { TEXT_CreateIndirect, guzhangdayin, ID_TEXT_3, 155, 116, 130, 30, 0, 0x0, 0 },
  { TEXT_CreateIndirect, qitadayin, ID_TEXT_4, 155, 151, 130, 30, 0, 0x0, 0 },
  { TEXT_CreateIndirect, yonghujibie, ID_TEXT_5, 6, 293, 130, 30, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "0", ID_TEXT_6, 277, 293, 206, 28, 0, 0x0, 0 },  { TEXT_CreateIndirect, w6_info, ID_TEXT_7, 0, 260, 400, 28, 0, 0x0, 0 },  { EDIT_CreateIndirect, "Edit", ID_EDIT_0, 290, 46, 30, 24, 0, 1, 0 },  { EDIT_CreateIndirect, "Edit", ID_EDIT_1, 290, 81, 30, 24, 0, 1, 0 },  { EDIT_CreateIndirect, "Edit", ID_EDIT_2, 290, 116, 30, 24, 0, 1, 0 },  { EDIT_CreateIndirect, "Edit", ID_EDIT_3, 290, 151, 30, 24, 0, 1, 0 },
  // USER START (Optionally insert additional widgets)
  // USER END
};

/*********************************************************************
*
*       Static code
*
**********************************************************************
*/

// USER START (Optionally insert additional static code)
// USER END

/*********************************************************************
*
*       _cbDialog
*/
static void _cbDialog(WM_MESSAGE * pMsg) {
  WM_HWIN hItem;
  // USER START (Optionally insert additional variables)
  // USER END

  switch (pMsg->MsgId) {  case WM_PAINT :       GUI_SetColor(HFM_HEAD_BK);       GUI_FillRect(0,0,480,30);       GUI_FillRect(0,290,480,320);       break;
  case WM_INIT_DIALOG:
    //
    // Initialization of 'Window'
    //        hItem = pMsg->hWin;
        WINDOW_SetBkColor(hItem, HFM_COLOR_BK);        hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_0);        EDIT_SetText(hItem,"N");          EDIT_EnableBlink(hItem, 300, 1);        EDIT_SetFont(hItem, GUI_FONT_20_1);        hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_1);        EDIT_SetText(hItem,"N");         EDIT_EnableBlink(hItem, 300, 1);        EDIT_SetFont(hItem, GUI_FONT_20_1);        hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_2);        EDIT_SetText(hItem,"N");        EDIT_EnableBlink(hItem, 300, 1);        EDIT_SetFont(hItem, GUI_FONT_20_1);        hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_3);        EDIT_SetText(hItem,"N");        EDIT_EnableBlink(hItem, 300, 1);       EDIT_SetFont(hItem, GUI_FONT_20_1);
    // USER START (Optionally insert additional code for further widget initialization)        hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_6);        _hwTime[5] = hItem;
       TEXT_SetFont(hItem, GUI_FONT_24_1);
       TEXT_SetTextAlign(hItem, GUI_TA_LEFT | GUI_TA_VCENTER);
       TEXT_SetText(hItem, timee);       hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_7);       TEXT_SetTextColor(hItem,HFM_COLOR_BY);  //  EDIT_EnableBlink(hItem, 300, 1);
    // USER START (Optionally insert additional code for further widget initialization)
    // USER END
    break;
  // USER START (Optionally insert additional message handling)
  // USER END
  default:
    WM_DefaultProc(pMsg);
    break;
  }
}

/*********************************************************************
*
*       Public code
*
**********************************************************************
*/void W6_PrintSetWindowDisplay(void)
{
  cursor = 0;
}
void W6_PrintSetWindowProcess(void)
{      EDIT_Handle hItem;       char *tempchar;
     switch(WinKeyValue)
     {
     case GUI_KEY_ENTER://ok键

          break;
     case GUI_KEY_HOME://菜单按钮
          break;
     case GUI_KEY_LEFT://左键
          break;
	 case GUI_KEY_UP://下键
	 case GUI_KEY_DOWN://下键         if(cursor <3)         {             cursor++;         }         else{            cursor = 0;         }	      GUI_SendKeyMsg(GUI_KEY_TAB, 1);
          break;
	 case GUI_KEY_ESCAPE://取消键
            break;
	case GUI_USR_KEY_ALARM://火警界面键
        break;
	case GUI_USR_KEY_FAULT://故障界面键
        break;
	case GUI_USR_KEY_SHEILD://屏蔽界面键
	    break;
	case GUI_USR_KEY_OUT://输出界面键
		break;
	case GUI_USR_KEY_SLIENCE://消音键
		break;
	case GUI_USR_KEY_RESET://复位键
		break;
	case GUI_KEY_F1://F1功能键       //cursor =  EDIT_GetCursorCharPos()        hItem = WM_GetDialogItem(W6_PrintSet_window, ID_EDIT_0+cursor);        EDIT_GetText(hItem,tempchar,2);        if(strcmp(tempchar,"Y")==0)        {            EDIT_SetText(hItem,"N");        }        else        {            EDIT_SetText(hItem,"Y");        }        GUI_Exec();
		break;
	case GUI_KEY_F2://F2功能键
		break;
	case '0':
		break;
	case '1':
	case '2':
	case '3':
	case '4':
    case '5':
	case '6':
	case '7':
	case '8':
	case '9':
		break;
	default :
			break;
     }
}
/*********************************************************************
*
*       CreateWindow
*/

WM_HWIN Create_W6_PrintSet_Window(void) {
  WM_HWIN hWin;

  hWin = GUI_CreateDialogBox(_aDialogCreate, GUI_COUNTOF(_aDialogCreate), _cbDialog, WM_HBKWIN, 0, 0);
  return hWin;
}

// USER START (Optionally insert additional public code)
// USER END

/*************************** End of file ****************************/
