/*********************************************************************
*                                                                    *
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                                                                    *
**********************************************************************
*                                                                    *
* C-file generated by:                                               *
*                                                                    *
*        GUI_Builder for emWin version 5.32                          *
*        Compiled Oct  8 2015, 11:59:02                              *
*        (c) 2015 Segger Microcontroller GmbH & Co. KG               *
*                                                                    *
**********************************************************************
*                                                                    *
*        Internet: www.segger.com  Support: support@segger.com       *
*                                                                    *
**********************************************************************
*/

// USER START (Optionally insert additional includes)
// USER END

#include "DIALOG.h"
#include "mygui_init.h"
/*********************************************************************
*
*       Defines
*
**********************************************************************
*/
#define ID_FRAMEWIN_0 (GUI_ID_USER + 0x01)
#define ID_TEXT_0 (GUI_ID_USER + 0x02)


// USER START (Optionally insert additional defines)
// USER END

/*********************************************************************
*
*       Static data
*
**********************************************************************
*/

// USER START (Optionally insert additional static data)
// USER END
unsigned char message_txt[] = "\xe6\x8c\x89<\xe7\xa1\xae\xe8\xae\xa4>\xe9\x94\xae\xe9\x80\x80\xe5\x87\xba\xef\xbc\x81";unsigned char baocunchengong[] = "\xe4\xbf\x9d\xe5\xad\x98\xe6\x88\x90\xe5\x8a\x9f\xef\xbc\x81";unsigned char shujucuowu[] = "\xe6\x95\xb0\xe6\x8d\xae\xe9\x94\x99\xe8\xaf\xaf\xef\xbc\x81";
// USER END
unsigned char *message_txt_const[] ={ baocunchengong,//保存成功 shujucuowu,//数据错误};
/*********************************************************************
*
*       _aDialogCreate
*/
static const GUI_WIDGET_CREATE_INFO _aDialogCreate[] = {
  { FRAMEWIN_CreateIndirect, "Message", ID_FRAMEWIN_0, 150, 100, 220, 150, 0, 0x0, 0 },
  { TEXT_CreateIndirect, baocunchengong, ID_TEXT_0, 50, 30, 96, 41, 0, 0x0, 0 },
  // USER START (Optionally insert additional widgets)
  // USER END
};

/*********************************************************************
*
*       Static code
*
**********************************************************************
*/

// USER START (Optionally insert additional static code)
// USER END

/*********************************************************************
*
*       _cbDialog
*/
static void _cbDialog(WM_MESSAGE * pMsg) {
  // USER START (Optionally insert additional variables)
  // USER END

  switch (pMsg->MsgId) {    case WM_PAINT :    WM_SetFocus(W_MessageBox);     GUI_SetFont(&GUI_Fontstay24);     GUI_SetColor(GUI_RED);     GUI_DispStringAt(message_txt, 15, 95);            break;
  // USER START (Optionally insert additional message handling)
  // USER END
  default:
    WM_DefaultProc(pMsg);
    break;
  }
}

/*********************************************************************
*
*       Public code
*
**********************************************************************
*/
/*********************************************************************
*
*       CreateFramewin
*/

WM_HWIN Create_MessageBox_Framewin(void) {
  WM_HWIN hWin;

  hWin = GUI_CreateDialogBox(_aDialogCreate, GUI_COUNTOF(_aDialogCreate), _cbDialog, WM_HBKWIN, 0, 0);   FRAMEWIN_SetMoveable(hWin,1);   FRAMEWIN_SetBarColor(hWin,1,HFM_HEAD_BK);   FRAMEWIN_SetClientColor(hWin,HFM_COLOR_BK);
  return hWin;
}/********************************************函数功能：显示消息框输入参数：data 显示的内容***********************************************/
void Show_Message(unsigned char data){     WM_HWIN hItem;    hItem = WM_GetDialogItem(W_MessageBox, ID_TEXT_0);
    TEXT_SetFont(hItem, &GUI_Fontstay24);
    TEXT_SetTextAlign(hItem, GUI_TA_LEFT | GUI_TA_VCENTER);
    TEXT_SetText(hItem, message_txt_const[data]);    WM_ShowWindow(W_MessageBox);}
// USER START (Optionally insert additional public code)
/*************************** End of file ****************************/
