/**********************************************************************                                                                    **                SEGGER Microcontroller GmbH & Co. KG                **        Solutions for real time microcontroller applications        **                                                                    ************************************************************************                                                                    ** C-file generated by:                                               **                                                                    **        GUI_Builder for emWin version 5.32                          **        Compiled Oct  8 2015, 11:59:02                              **        (c) 2015 Segger Microcontroller GmbH & Co. KG               **                                                                    ************************************************************************                                                                    **        Internet: www.segger.com  Support: support@segger.com       **                                                                    ************************************************************************/// USER START (Optionally insert additional includes)// USER END#include "DIALOG.h"#include "mygui_init.h"/***********************************************************************       Defines************************************************************************/#define ID_FRAMEWIN_0 (GUI_ID_USER + 0x00)#define ID_EDIT_0 (GUI_ID_USER + 0x01)#define ID_TEXT_0 (GUI_ID_USER + 0x02)#define ID_TEXT_1 (GUI_ID_USER + 0x03)// USER START (Optionally insert additional defines)// USER END/***********************************************************************       Static data************************************************************************/unsigned char qingshurumima[] = "\xe8\xaf\xb7\xe8\xbe\x93\xe5\x85\xa5  \xe7\xba\xa7\xe5\xaf\x86\xe7\xa0\x81";unsigned char anquerenjian[] = "\xe6\x8c\x89<\xe7\xa1\xae\xe8\xae\xa4>\xe9\x94\xae\xe9\x80\x80\xe5\x87\xba";// USER START (Optionally insert additional static data)// USER END/***********************************************************************       _aDialogCreate*/static const GUI_WIDGET_CREATE_INFO _aDialogCreate[] = {  { FRAMEWIN_CreateIndirect, "Password", ID_FRAMEWIN_0, 150, 100, 220, 150, 0, 0x0, 0 },  { EDIT_CreateIndirect, "Edit", ID_EDIT_0, 62, 53, 80, 20, 0, 0x4, 0 },  { TEXT_CreateIndirect, qingshurumima, ID_TEXT_0, 9, 18, 200, 30, 0, 0x0, 0 },  { TEXT_CreateIndirect, anquerenjian, ID_TEXT_1, 9, 85, 200, 30, 0, 0x0, 0 },  // USER START (Optionally insert additional widgets)  // USER END};/***********************************************************************       Static code************************************************************************/// USER START (Optionally insert additional static code)// USER END/***********************************************************************       _cbDialog*/static void _cbDialog(WM_MESSAGE * pMsg) {  WM_HWIN hItem;  int     NCode;  int     Id;  // USER START (Optionally insert additional variables)  // USER END  switch (pMsg->MsgId) {case WM_PAINT:     GUI_SetFont(GUI_FONT_24_ASCII);     GUI_SetColor(GUI_BLACK);     GUI_DispStringAt("1", 100, 22);//显示密码输入级别    hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_0);    EDIT_SetText(hItem, "");    break;  case WM_INIT_DIALOG:    //    // Initialization of 'Password'    //    hItem = pMsg->hWin;    FRAMEWIN_SetFont(hItem, GUI_FONT_20_ASCII);    //    // Initialization of 'Edit'    //    hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_0);    EDIT_SetText(hItem, "");    EDIT_SetFont(hItem, GUI_FONT_20_ASCII);    EDIT_EnableBlink(hItem, 300, 1);    //    // Initialization of 'Text'    //    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_0);    TEXT_SetFont(hItem, &GUI_Fontstay24);    TEXT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);    //    // Initialization of 'Text'    //    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_1);    TEXT_SetFont(hItem, &GUI_Fontstay24);    TEXT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);    // USER START (Optionally insert additional code for further widget initialization)    // USER END    break;  case WM_NOTIFY_PARENT:    Id    = WM_GetId(pMsg->hWinSrc);    NCode = pMsg->Data.v;    switch(Id) {    case ID_EDIT_0: // Notifications sent by 'Edit'      switch(NCode) {      case WM_NOTIFICATION_CLICKED:        // USER START (Optionally insert code for reacting on notification message)        // USER END        break;      case WM_NOTIFICATION_RELEASED:        // USER START (Optionally insert code for reacting on notification message)        // USER END        break;      case WM_NOTIFICATION_VALUE_CHANGED:        // USER START (Optionally insert code for reacting on notification message)        // USER END        break;      // USER START (Optionally insert additional code for further notification handling)      // USER END      }      break;    // USER START (Optionally insert additional code for further Ids)    // USER END    }    break;  // USER START (Optionally insert additional message handling)  // USER END  default:    WM_DefaultProc(pMsg);    break;  }}/***********************************************************************       Public code************************************************************************/void W27_PasswordMessageBoxDisplay(void){}void W27_PasswordMessageBoxProcess(void){     switch(WinKeyValue)
     {
     case GUI_KEY_ENTER://ok键
          WM_HideWindow(W_PasswoedMessageBox);          if(WinPasswordMode == WIN_PASSWORD_SET)          {            WinLoad(WINDOW_SYSSET_INDEX);          }
          break;
     case GUI_KEY_HOME://菜单按钮
          break;
     case GUI_KEY_LEFT://左键
          break;
	 case GUI_KEY_UP://下键
          break;
	 case GUI_KEY_DOWN://下键
          break;
	 case GUI_KEY_ESCAPE://取消键          GUI_SendKeyMsg(GUI_KEY_BACKSPACE, 1);
            break;
	case GUI_USR_KEY_ALARM://火警界面键
        break;
	case GUI_USR_KEY_FAULT://故障界面键
        break;
	case GUI_USR_KEY_SHEILD://屏蔽界面键
	    break;
	case GUI_USR_KEY_OUT://输出界面键
		break;
	case GUI_USR_KEY_SLIENCE://消音键
		break;
	case GUI_USR_KEY_RESET://复位键
		break;
	case GUI_KEY_F1://F1功能键
		break;
	case GUI_KEY_F2://F2功能键         GUI_SendKeyMsg(GUI_KEY_BACKSPACE, 1);
		break;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
    case '5':
	case '6':
	case '7':
	case '8':
	case '9':
		break;
	default :
			break;
     }}/***********************************************************************       CreatePassword*/WM_HWIN CreatePassword(void) {  WM_HWIN hWin;  hWin = GUI_CreateDialogBox(_aDialogCreate, GUI_COUNTOF(_aDialogCreate), _cbDialog, WM_HBKWIN, 0, 0);  return hWin;}// USER START (Optionally insert additional public code)// USER END/*************************** End of file ****************************/